### ISSUE TITLE
Add a merge scope option

### ISSUE THREAD

**Issue by victornoel** [ferstl/depgraph-maven-plugin#10]
Hi,

Sometimes, it could be needed to consider that dependencies with the same groupId:artifactId:version but different scope are the same dependency.

It would be nice to have an option to merge the scope altogether!

**Comment by ferstl** [comment]
This feature has already been requested a few times. I'll take a look.

**Comment by ferstl** [comment]
A first implementation is available now in the `aggregate` goal: `-DmergeScopes=true/false` (Default is `true` at the moment)

**Comment by victornoel** [comment]
Excellent, is there a reason for not implementing it in `graph` too?

**Comment by ferstl** [comment]
You will never have multiple scopes with the `graph` goal. This goal works on a single maven project where dependency resolution is unambiguous.

**Comment by ferstl** [comment]
Done, the `mergeScopes` option is available in the `aggregate` and `aggregate-by-groupId` goals.
I am currently working on Version 1.1 (or maybe version 2.0) of the plugin. So it will take a bit more time until you get a new version on Maven Central.

**Comment by victornoel** [comment]
> You will never have multiple scopes with the graph goal. This goal works on a single maven project where dependency resolution is unambiguous.

Of course yes! Thanks for all of this, I already started experimenting the different options you introduced and it is helpful :)
