### ISSUE TITLE
Command line setting of "With GroupId" isn't obvious and isn't explicitly documented

### ISSUE THREAD

**Issue by paul-hammant** [ferstl/depgraph-maven-plugin#100]
There from the README for depgraph-maven-plugin:

![image](https://user-images.githubusercontent.com/82182/55250109-6d363180-5245-11e9-94e3-3e811297d072.png)

Soooo, I've no idea how to activate that. I'm trying alternates, but none appear to work:

* -DgroupIds=true
* -DGroupIds=true
* -DwithgroupIds=true
* -DwithGroupIds=true

I'm just guessing :-(

README could do with making that 100% clear, IMO

**Comment by ferstl** [comment]
Hi
The correct answer is `-DshowGroupIds` (`=true` is not necessary) :-)
Have you seen the [Plugin Documentation](https://ferstl.github.io/depgraph-maven-plugin/plugin-info.html)? It shows all goals and all available options. The README refers to that documentation for further details. The plugin has too many options to mention them all in the README.
