### ISSUE TITLE
Example JSON configuration?

### ISSUE THREAD

**Issue by paul-hammant** [ferstl/depgraph-maven-plugin#101]
Hey, is there an example `configuration.json` in the documentation?  I'm trying to see how to specify `showDuplicates=true` should work, and I've tried it as a Maven `-D` parameter, but that was ignored, so I think it should in `configuration.json` but don't know where to start there.

**Comment by paul-hammant** [comment]
OK, so there's no JSON configuration that would match the <configugration/> block of the <plugin> in the pom. That's where all of the config would do and if one needs multiple different diagrams from the same project, one should use <profiles> in the pom for that. The command line `-D` parameters are a subset of what's capable in the pom/build/plugin/configuration section.

**Comment by ferstl** [comment]
Hi,
Setting `-DshowDuplicates` on the command line should work as well as configuring it in the POM file. Duplicate dependencies will be shown as black dashed arrows by default in the graph. However, the "aggregate" goal does not support showing duplicates. The FAQ at the bottom of the [README](https://github.com/ferstl/depgraph-maven-plugin/blob/master/README.md) explains why. If it did not work with the "graph" goal (which supports duplicates), I would be interested why. An example project to reproduce the problem would be nice then.

The `-D` parameters are not a subset of the options that you can configure in the POM file. The [plugin documentation](https://github.com/ferstl/depgraph-maven-plugin/blob/master/README.md#faq) shows the corresponding `-D` options under "User property is:". They should all be similar to the configuration options in the POM file.

I guess, you are referring to the style configuration by mentioning `configuration.json`. You can find some documentation about styling in the [Wiki](https://github.com/ferstl/depgraph-maven-plugin/wiki/Styling). You can find the default style configurations of the plugin [here](https://github.com/ferstl/depgraph-maven-plugin/wiki/Styling). Further examples are in the [test resources](https://github.com/ferstl/depgraph-maven-plugin/tree/master/src/test/resources) of the plugin.

I hope that helps.
