### ISSUE TITLE
Scope enhancement: "compile-only" addition

### ISSUE THREAD

**Issue by tazous** [ferstl/depgraph-maven-plugin#106]
Hello and first of all, thanks for this great work!

I would like to have a graph of "direct" dependencies (so I can clearly see how my modules are linked), without "provided" ones.
For this, I currently use the "runtime" scope but it seems like sub-dependencies of "provided" dependencies may in some cases appear as "directly" included by current projects. This occurs when they are also part of sub-dependencies of "compile" scope included projects. I assume it is because they are now considered as "runtime" dependencies which totally makes sense that is why a "compile-only" scope would be a great addition

In order to better illustrate what I say, let's assume following dependencies:
project A -> "compile" -> project B
project A -> "provided" -> project C
project B -> "compile" -> project D
project C -> "compile" -> project D

When generating a graph with "compile" scope, I have the following lines drawn:
A ---> B ---> D
A ---> C ---> D
When generating a graph with "runtime" scope, I have the following lines drawn:
A ---> B ---> D
A ---> D
A "compile-only" scope would just generate the following line:
A ---> B ---> D

**Comment by ferstl** [comment]
Hi

As I understand it, you are using the "graph" goal on Project A together with "-Dscope=compile". Is that correct?
The name of the "scope" option is a bit misleading as it relates to the classpath that Maven uses for a specific scope and not for the scopes that are declared in the POM files. So when you define the "scope" option, this is what you will get:

- compile: Shows compile, provided and system dependencies
- provided: Shows provided dependencies
- runtime: Shows compile and runtime dependencies
- system: Shows system dependencies
- test (default): Shows all dependencies

This behavior is also mentioned in the [plugin documentation](https://ferstl.github.io/depgraph-maven-plugin/graph-mojo.html).


For your example with the runtime scope I assume you should get this graph:
A ---> B ---> D
A ---> C (not A -> D)

At the moment the plugin does not have an option for filtering declared scopes. I'll check if this can be implemented.

**Comment by tazous** [comment]
Hello Stefan and thank you for your reactivity,
In my use case, I run the "graph" goal on Project A altogether with "-Dscope=runtime" because "-Dscope=compile" generates way too much dependencies for me (especially provided ones)

but with runtime scope, I **do** get the following graph:
A ---> B ---> D
A ---> **D**

A because it is the project where I'm running the build
B because A is linked with it using "compile"
D because B is linked with it using "compile"
C is not present because A is linked with it using "provided"
AND an extra link between A and D because A is linked to D "through" C at runtime (at least that is the reason I found for this link to be present)

**Comment by tazous** [comment]
In order to better illustrate it, here is an example of what produces "mvn dependency:tree" on my project:

com.conztanz.event:event-model:jar:1.6-SNAPSHOT
+- com.conztanz.framework:framework-model:jar:0.8-SNAPSHOT:compile
|  +- com.conztanz.framework:framework-json:jar:0.8-SNAPSHOT:compile
|  |  +- com.conztanz.framework:framework-commons:jar:0.8-SNAPSHOT:compile
|  |  |  +- commons-collections:commons-collections:jar:3.2.2:compile
|  |  |  +- commons-io:commons-io:jar:2.6:compile
|  |  |  +- org.apache.commons:commons-lang3:jar:3.7:compile
|  |  |  \- joda-time:joda-time:jar:2.9.9:compile
|  |  +- org.springframework:spring-web:jar:4.3.9.RELEASE:compile
|  |  |  \- org.springframework:spring-context:jar:4.3.9.RELEASE:compile
|  |  |     \- org.springframework:spring-expression:jar:4.3.9.RELEASE:compile
|  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.8:compile
|  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0:compile
|  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.8.8:compile
|  |  +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.8.8:compile
|  |  +- com.fasterxml.jackson.datatype:jackson-datatype-hibernate5:jar:2.8.8:compile
|  |  \- com.fasterxml.jackson.module:jackson-module-jsonSchema:jar:2.8.8:compile
|  |     \- javax.validation:validation-api:jar:1.1.0.Final:compile
|  +- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.2.Final:compile
|  +- org.hibernate:hibernate-core:jar:5.0.12.Final:compile
|  |  +- org.jboss.logging:jboss-logging:jar:3.3.1.Final:compile
|  |  +- org.javassist:javassist:jar:3.21.0-GA:compile
|  |  +- antlr:antlr:jar:2.7.7:compile
|  |  +- org.jboss:jandex:jar:2.0.0.Final:compile
|  |  +- dom4j:dom4j:jar:1.6.1:compile
|  |  |  \- xml-apis:xml-apis:jar:1.4.01:compile
|  |  \- org.hibernate.common:hibernate-commons-annotations:jar:5.0.1.Final:compile
|  \- org.jadira.usertype:usertype.core:jar:5.0.0.GA:compile
|     +- org.slf4j:slf4j-api:jar:1.7.25:compile
|     \- org.jadira.usertype:usertype.spi:jar:5.0.0.GA:compile
+- com.conztanz.event:event-test:jar:1.6-SNAPSHOT:test
|  \- com.conztanz.event:event-testing:jar:1.6-SNAPSHOT:test
|     +- com.conztanz.framework:framework-testing:jar:0.8-SNAPSHOT:test
|     |  +- junit:junit:jar:4.12:test
|     |  |  \- org.hamcrest:hamcrest-core:jar:1.3:test
|     |  +- org.easymock:easymock:jar:3.2:test
|     |  |  +- cglib:cglib-nodep:jar:2.2.2:test
|     |  |  \- org.objenesis:objenesis:jar:1.3:test
|     |  +- org.springframework:spring-test:jar:4.3.9.RELEASE:test
|     |  +- org.postgresql:postgresql:jar:9.4.1212.jre7:test
|     |  +- org.apache.activemq:activemq-broker:jar:5.15.9:test
|     |  |  +- org.apache.activemq:activemq-openwire-legacy:jar:5.15.9:test
|     |  |  \- com.google.guava:guava:jar:24.1-jre:test
|     |  |     +- com.google.code.findbugs:jsr305:jar:1.3.9:test
|     |  |     +- org.checkerframework:checker-compat-qual:jar:2.0.0:test
|     |  |     +- com.google.errorprone:error_prone_annotations:jar:2.1.3:test
|     |  |     +- com.google.j2objc:j2objc-annotations:jar:1.1:test
|     |  |     \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:test
|     |  +- org.apache.activemq:activemq-client:jar:5.15.9:test
|     |  |  +- org.fusesource.hawtbuf:hawtbuf:jar:1.11:test
|     |  |  \- org.apache.geronimo.specs:geronimo-j2ee-management_1.1_spec:jar:1.0.1:test
|     |  \- org.apache.activemq:activemq-spring:jar:5.15.9:test
|     |     +- org.apache.xbean:xbean-spring:jar:4.2:test
|     |     \- org.apache.commons:commons-pool2:jar:2.4.2:test
|     \- com.conztanz.framework:framework-model:test-jar:tests:0.8-SNAPSHOT:test
\- com.conztanz.framework:framework-aop:jar:0.8-SNAPSHOT:test
   +- org.springframework:spring-aop:jar:4.3.9.RELEASE:compile
   |  +- org.springframework:spring-beans:jar:4.3.9.RELEASE:compile
   |  \- org.springframework:spring-core:jar:4.3.9.RELEASE:compile
   |     \- commons-logging:commons-logging:jar:1.2:compile
   +- org.springframework:spring-aspects:jar:4.3.9.RELEASE:test
   |  \- org.aspectj:aspectjweaver:jar:1.8.10:test
   \- org.aspectj:aspectjrt:jar:1.8.10:test

and what is produced when using "-Dscope=runtime"

![event-model](https://user-images.githubusercontent.com/5639176/70161794-f4815200-16bc-11ea-9c37-c8cb408c304f.png)

we can see that a link is drawn between even-model & spring-aop (and it should not) because 
event-model---(test)-->event-test---(test)-->framework-aop---(compile)-->spring-aop
as if it were due to transitivity...

**Comment by ferstl** [comment]
ok, I‘ll take a look

**Comment by ferstl** [comment]
I created a new issue to improve the scope handling: #107

**Comment by ferstl** [comment]
I improved the scope handling for version 4.0.0. There is a new parameter `-Dscopes` where you can filter for the exact scopes of your dependencies, e.g. `-Dscopes=compile,test`. The former `-Dscope` parameter (note the missing `s`) has been deprecated and replaced by `-DclasspathScope`.
However, it will take a little while for this version to be released because I am working on two more features for that release. If you like to try it, you can build a SNAPSHOT version of this plugin from the master branch:

```
git clone https://github.com/ferstl/depgraph-maven-plugin.git
cd depgraph-maven-plugin

# The tests will take a few minutes
mvn clean install -DskipTests
```

**Comment by ferstl** [comment]
Version 4.0.0 will be on Maven Central soon.
