### ISSUE TITLE
how can i merge multi project into one gragh

### ISSUE THREAD

**Issue by MonkAscetic** [ferstl/depgraph-maven-plugin#115]
I have multiple Maven projects instead of multiple modules, which call each other. How can I get their call graph.

**Comment by MonkAscetic** [comment]
i want merge all project. I think i can write a script to merge all of gragh but i think this is a bad idea,do you have a better idea

**Comment by ferstl** [comment]
Hi

I think the easiest solution to just get an overall graph is to create an artificial maven project that contains all of your independent projects either as modules or as dependencies. On that you can execute `depgraph:aggregate` (in case you are using modules) or `depgraph:graph` (in case you are using dependencies).

Cheers,
Stefan

**Comment by ferstl** [comment]
@MonkAscetic I‘m closing this question for now. Feel free to re-open in case my answer does not work for you.
