### ISSUE TITLE
Graph creation works from command-line but not from POM execution

### ISSUE THREAD

**Issue by raedma** [ferstl/depgraph-maven-plugin#123]
I tried integration the `depgraph-maven-plugin` into the POM of a project as described [here](dependency-graph.dot)

    
    <plugin>
        <groupId>com.github.ferstl</groupId>
        <artifactId>depgraph-maven-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
            <createImage>true</createImage>
            <showConflicts>true</showConflicts>
            <showDuplicates>true</showDuplicates>
            <showGroupIds>true</showGroupIds>
            <showVersions>true</showVersions>
        </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>graph</goal>
                </goals>
            </execution>
        </executions>
    </plugin>

However, no `dependency-graph.dot` was created during a build of the project (Netbeans 12.0). I can however create the file from the command line using `mvn depgraph:graph`. What am I missing in the configuration? I would like to create a new dependency-graph after each build (`mvn:install`). I use Apache Maven 3.6.3.

**Comment by ferstl** [comment]
Hi @raedma
The configuration looks almost good to me. I think you need to link the plugin execution to a phase in the build lifecycle, i.e. you should add a <phase> to the plugin execution. See also https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html . Make also sure that your configuratin is located under build/plugins and not under build/pluginManagement/plugins in your POM file.

**Comment by raedma** [comment]
Ok, thanks for the tip with the phase assignment. The following did the trick:

    
    <plugin>
        <groupId>com.github.ferstl</groupId>
        <artifactId>depgraph-maven-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
            <createImage>true</createImage>
            <showConflicts>true</showConflicts>
            <showDuplicates>true</showDuplicates>
            <showGroupIds>true</showGroupIds>
            <showVersions>true</showVersions>
        </configuration>
        <executions>
            <execution>
                <phase>install</phase>
                <goals>
                    <goal>graph</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
