### ISSUE TITLE
Missing dependency arrows in graph?

### ISSUE THREAD

**Issue by achimmihca** [ferstl/depgraph-maven-plugin#126]
I fear that this plugin is ignoring some of my dependencies.

The [wiki](https://github.com/ferstl/depgraph-maven-plugin/wiki/Dependency-Graph-Construction) claims:

> (*) The resolved dependencies of a maven module do always form a tree. There are neither cycles nor different paths from one dependency to another. 

A tree does not have cycles, yes. But there can be different paths from one node to another. Example: A->B, A->C, B->D, C->D. In this diamond shaped tree, you can go from A to D via B or via C.

My dependencies have a similar structure and some dependencies are not shown.
Is this a known limitation? Could it be fixed?

Note that `mvn dependency:tree` does show all my dependencies, including diamond shaped ones.

BTW: I thought this to be an excellent plugin so far. However, if it is ignoring dependencies, then it is pretty much useless for me.

**EDIT:**
I just found that `mvn dependency:tree -DoutputType=dot` is also able to create a dot file. Sadly, it is lacking the same dependency edges as depgraph plugin. I found this on [StackOverflow](https://stackoverflow.com/a/36048979/4412885).

I would be grateful, if depgraph plugin could be configured to show all dependencies and export them to a dot file.

When I run `mvn dependency:tree -Dverbose`, then it shows me some dependencies as "omitted for duplicate". These are the additional edges that I am missing in the current diagram. You might include a "verbose" option in your plugin as well to show these.

**Comment by achimmihca** [comment]
Ok, now that I understand the issue, I see that the option `showDuplicates` of this plugin is exactly what I am looking for.

Conclusion: to show all dependencies that are specified in the pom.xml files, use `<showDuplicates>true</showDuplicates>`.

Many thanks, this plugin is really nice!

**Comment by ferstl** [comment]
@achimmihca There is also an option `showConflicts` which will show dependencies with conflicting versions. Example: https://raw.githubusercontent.com/ferstl/depgraph-maven-plugin/master/src/doc/duplicates-and-conflicts.png
