### ISSUE TITLE
 Failed to execute goal com.github.ferstl:depgraph-maven-plugin:3.3.0:graph (default-cli) on project cntrreg-sidecar: Execution default-cli of goal com.github.ferstl:depgraph-maven-plugin:3.3.0:graph failed: A required class was missing while executing com.github.ferstl:depgraph-maven-plugin:3.3.0:graph: org/apache/commons/lang3/StringUtil

### ISSUE THREAD

**Issue by zmaxyan** [ferstl/depgraph-maven-plugin#133]
Using maven Apache Maven 3.3.9, when running mvn depgraph:graph gives error: Failed to execute goal com.github.ferstl:depgraph-maven-plugin:3.3.0:graph (default-cli) on project cntrreg-sidecar: Execution default-cli of goal com.github.ferstl:depgraph-maven-plugin:3.3.0:graph failed: A required class was missing while executing com.github.ferstl:depgraph-maven-plugin:3.3.0:graph: org/apache/commons/lang3/StringUtil

**Comment by ferstl** [comment]
@zmaxyan I am not able to reproduce this error with version 3.3.9 . Can you point me to an example project where you got this error. Or could you provide me with your configuration of the depgraph-maven-plugin?
