### ISSUE TITLE
configure a layout engine

### ISSUE THREAD

**Issue by delanym** [ferstl/depgraph-maven-plugin#139]
I know I can do it myself, but can the plugin be configured to pass through a layout engine?
http://www.graphviz.org/doc/info/command.html#-K

**Comment by gregorydlogan** [comment]
Seconding this.  I've got a rather large svg here that my browser is telling me renders by default at 17785pt x 827pt.  I can fix that by adding `nodesep` and `ranksep` manually, but it'd be nice to be able to slap that into the plugin config or something.

**Comment by ferstl** [comment]
I'll take a look

**Comment by ferstl** [comment]
Version 4.0.0 will be on Maven Central soon. There, you can use a new parameter `dotArguments` where you can define additional options for the `dot` executable.

**Comment by delanym** [comment]
Works as advertised! Thank you so much.
