### ISSUE TITLE
Support a new "scope" that includes current "compile" and "runtime" scopes together

### ISSUE THREAD

**Issue by fernandosci** [ferstl/depgraph-maven-plugin#140]
Hi,

First of all thanks for this great plugin!

The current released version supports the following scopes as described in the plugin documentation

- compile: Shows compile, provided, and system dependencies
- provided: Shows provided dependencies
- runtime: Shows compile and runtime dependencies
- system: Shows system dependencies
- test (default): Shows all dependencies

Would it be possible to support a new scope that consolidates the current supported compile and runtime scopes? So that the effective dependency graph would include all declared scopes except the test.

Feature #107 would actually cover this use case but as I understood it will only be released in the 4.x version. Maybe this new scope could be introduced and released sooner in version 3.4.x

**Comment by ferstl** [comment]
Hi,
Does anything prevent you from using Version 4 when it is released. I plan to release the new version soon.

**Comment by fernandosci** [comment]
Hi,
Thanks for the quick response!
At first, I believe nothing will prevent using version 4. I would have to double-check but as long the structure of output in .json format does not change it wouldn't have problems.

Would you happen to have an estimated date for releasing version 4? or maybe an indication in terms of weeks or months?

**Comment by ferstl** [comment]
Version 4.0.0 will be on Maven Central soon.
