### ISSUE TITLE
multiple projects

### ISSUE THREAD

**Issue by quantrpeter** [ferstl/depgraph-maven-plugin#152]
Hi. Does this support multiple projects? Analyzt the dependency at once for multiple projects? I got many maven projects that referencing each other, I need to see a graph. thanks

**Comment by ferstl** [comment]
Hi,
The plugin works for single-module and for multi-module projects. However, you can run it only at one Maven project at a time (same as with Maven itself).
Take a look a the `aggregate` goals for multi-module projects. If you run the `graph` goal on a multi-module project, it will create a graph for each module individually.

**Comment by quantrpeter** [comment]
thanks
