### ISSUE TITLE
Can one "style" .puml files? 

### ISSUE THREAD

**Issue by mmoser18** [ferstl/depgraph-maven-plugin#166]
I am now (almost - see different issue) there to automatically create the dependency graph(s) for our project. I am creating .puml files. 

One issue that remains is, that the dotted connections (test dependencies) use a gray that so light that these connections are almost invisible when printed. Is there some mechanism or option to "style" these diagrams a bit so I could define a slightly darker color?

**Comment by ferstl** [comment]
Hi @mmoser18 
Unfortunately there is no way to style the .puml dependency graphs. I can change the color from `#D3D3D3` to a darker grey in the next release. Until then you might add some post-processing step in your build that changes the `#D3D3D3` color code to something you like.

Cheers,
Stefan

**Comment by mmoser18** [comment]
Thanks for responding. And - yes - a darker default color will help. Thanks!
