### ISSUE TITLE
Mention that -D prefix is needed for includes (etc)

### ISSUE THREAD

**Issue by paul-hammant** [ferstl/depgraph-maven-plugin#21]
It's not clear, without. Other optional params too, I suspect.

**Comment by ferstl** [comment]
Using system properties (`-D`) to configure a Maven plugin on the command line is a [well-documented](https://maven.apache.org/guides/mini/guide-configuring-plugins.html) mechanism in Maven:

> For mojos that are intended to be executed directly from the CLI, their parameters usually provide a means to be configured via system properties instead of a <configuration> section in the POM.

When you take a look at the plugin documentation, e.g. the [`includes`](https://ferstl.github.io/depgraph-maven-plugin/aggregate-mojo.html#includes) property, the "User Property" part describes the Java system property for the command line.

> List of artifacts to be included in the form of groupId:artifactId:type:classifier.
>
>   - Type: java.util.List
>   - Since: 1.0.0
>   - Required: No
>   - User Property: includes

So in this example, you need to specify `-Dincludes=...` on the command line.
