### ISSUE TITLE
feature request: exclude variant

### ISSUE THREAD

**Issue by pmendelson** [ferstl/depgraph-maven-plugin#22]
The excludes parameter is quite useful for removing clutter from a dependency graph.  What would also be useful would be a parameter, referred to in this issue as "terminalModules", in which each module in this list would be displayed on the graph but none of it's dependencies would be followed.

For example, I might declare 
```xml
<terminalModules>org.springframework:*</terminalModules>
```

To show where my modules reference spring modules but not show any references to spring modules from other spring modules.

**Comment by ferstl** [comment]
Have you looked at the [`includes`](https://ferstl.github.io/depgraph-maven-plugin/graph-mojo.html#includes) parameter? It is available in all goals and should do exactly what you need.
For example:

    <includes>
      <include>org.springframework:*</include>
    </includes>

If not, please let me know.

**Comment by pmendelson** [comment]
I made a graph with the following:
```xml
<includes>
  <include>proj.mine:*</include>
  <include>org.springframework:*</include>
</includes>
```
and got the following (slightly redacted) dot
```xml
digraph "big-service" {
  graph[rankdir="LR"]
  node [shape="box",style="rounded",fontname="Helvetica",fontsize="14"]
  edge [fontsize="10",fontname="Helvetica"]

  // Node Definitions:
  "proj.mine:big-service:war:"[label=<<font point-size="10">proj.mine</font><br/>big-service<font point-size="10"><br/>16.09.01-SNAPSHOT</font>>]
  "proj.mine:eclkc-model:jar:"[label=<<font point-size="10">proj.mine</font><br/>eclkc-model<font point-size="10"><br/>16.09.01-SNAPSHOT</font>>]
  "proj.mine:model1:jar:"[label=<<font point-size="10">proj.mine</font><br/>model1<font point-size="10"><br/>16.09.00</font>>]
  "proj.mine:shared-model:jar:"[label=<<font point-size="10">proj.mine</font><br/>shared-model<font point-size="10"><br/>16.09.00</font>>]
  "org.springframework:spring-orm:jar:"[label=<<font point-size="10">org.springframework</font><br/>spring-orm<font point-size="10"><br/>4.2.2.RELEASE</font>>]
  "proj.mine:model2:jar:"[label=<<font point-size="10">proj.mine</font><br/>model2<font point-size="10"><br/>16.09.00</font>>]
  "org.springframework:spring-core:jar:"[label=<<font point-size="10">org.springframework</font><br/>spring-core<font point-size="10"><br/>4.2.2.RELEASE</font>>]
  "org.springframework:spring-tx:jar:"[label=<<font point-size="10">org.springframework</font><br/>spring-tx<font point-size="10"><br/>4.2.2.RELEASE</font>>]
  "org.springframework:spring-beans:jar:"[label=<<font point-size="10">org.springframework</font><br/>spring-beans<font point-size="10"><br/>4.2.2.RELEASE</font>>]
  "org.springframework:spring-context:jar:"[label=<<font point-size="10">org.springframework</font><br/>spring-context<font point-size="10"><br/>4.2.2.RELEASE</font>>]
  "org.springframework:spring-expression:jar:"[label=<<font point-size="10">org.springframework</font><br/>spring-expression<font point-size="10"><br/>4.2.2.RELEASE</font>>]
  "org.springframework:spring-web:jar:"[label=<<font point-size="10">org.springframework</font><br/>spring-web<font point-size="10"><br/>4.2.2.RELEASE</font>>]
  "org.springframework:spring-aop:jar:"[label=<<font point-size="10">org.springframework</font><br/>spring-aop<font point-size="10"><br/>4.2.2.RELEASE</font>>]
  "org.springframework:spring-context-support:jar:"[label=<<font point-size="10">org.springframework</font><br/>spring-context-support<font point-size="10"><br/>4.2.2.RELEASE</font>>]
  "org.springframework:spring-jdbc:jar:"[label=<<font point-size="10">org.springframework</font><br/
>spring-jdbc<font point-size="10"><br/>4.2.2.RELEASE</font>>]
```

My expectation with the feature request was that spring-tx would not be on the graph because it is a transitive dependency outside of spring.  Currently I would need to change my config to
```xml
<includes>
  <include>proj.mine:*</include>
  <include>org.springframework:*</include>
</includes>
<excludes>
  <exclude>org.springframework:spring-tx</exclude>
</includes>
```
But if I did that I would never notice when one of the modules in proj.mine picked up a direct dependency on spring-tx

**Comment by pmendelson** [comment]
If you consider implementing this feature (which, in my opinion, is a cousin of <targetIncludes>) another approach might be
```xml
<artifactGroup>
  <includes>...</includes>
  <excludes>...</excludes>
  <onGraph>true|false</onGraph>
  <followDependencies>false|true</followDependencies >
  <asTargetOnly>false|true</asTargetOnly>
  <nodeStyle>default|some name</nodeStyle>
</artifactGroup>

**Comment by ferstl** [comment]
Would it work for you to have a new flag that enables/disables resolution of transitive dependencies? For example:

    <resolveTransitiveDependencies>false</resolveTransitiveDependencies>
    <includes>
      <include>proj.mine:*</include>
      <include>org.springframework:*</include>
    </includes>

The graph would then only show artifacts of your project (`proj.mine:*`) and direct dependencies to the spring framework.

**Comment by pmendelson** [comment]
A global resolveTransitiveDependencies would be helpful.  The best option for my uses would be to declare resolveTransitiveDependencies differently for different artifacts. resolveTransitiveDependencies should be true for my modules but it should be false for spring or hibernate modules.

**Comment by ferstl** [comment]
@pmendelson I will add the two new options `transitiveIncludes` and `transitiveExcludes` to the plugin.
So a configuration like this should help:
```
<targetIncludes>org.springframework:*</targetIncludes>
<transitiveExcludes>org.springframework:*</transitiveExcludes >
```

This configuration will show all direct (i.e. declared) dependencies to Spring but not the transitive ones.

**Comment by ferstl** [comment]
Version 3.0.0 is available on Maven Central
