### ISSUE TITLE
provide graph level directives (mostly for dot options)

### ISSUE THREAD

**Issue by pmendelson** [ferstl/depgraph-maven-plugin#23]
When I run my dependency graph I always add 1 line to my .dot file:
```java
digraph "big-service" {
   graph[rankdir="LR"]
   node [shape="box",style="rounded",fontname="Helvetica",fontsize="14"]
   edge [fontsize="10",fontname="Helvetica"]

   // Node Definitions:
   …

   // Edge Definitions:
   …
}
```
It would be great to be able to provide attribute pairs to go into the "graph" directive

**Comment by ferstl** [comment]
I added a new styling option for this. With this [style configuration](https://github.com/ferstl/depgraph-maven-plugin/wiki/Styling) you'll get a left-to-right directed graph:

    {
      "graph": {
        "rankdir": "LR"
      }
    }

I'll close the ticket as soon as a new release of the plugin is available.

**Comment by ferstl** [comment]
Version 2.2.0 will be on Maven Central within the next few hours.
