### ISSUE TITLE
Any way to generate in a top-down direction?

### ISSUE THREAD

**Issue by marcgise** [ferstl/depgraph-maven-plugin#24]
Hi,

Does exist any option to generate the graph in a top-down direction? I mean, I'm launching the `mvn depgraph:graph` from the parent project, and only if I go to the X child project I found the tree dependencies from the point of view of this project.

But I want to get the tree dependencies of all the projects that are "soons" of the parent project.

Thanks

**Comment by ferstl** [comment]
Hi,
The `graph` goal creates a dependency graph for each individual module in your maven project.
An alternative to that is the [`aggregate`](https://ferstl.github.io/depgraph-maven-plugin/aggregate-mojo.html) goal which will create one single graph over a multi-module project. If you only want to see the modules of your project (if I understand you correctly), you may use the `includes` option. For example, if you have a multi-module project where each of your modules share the same groupId `com.mycompany.myproject`, you could use `com.mycompany.myproject:*` as `includes` option.

**Comment by ferstl** [comment]
@marcgise Did my comment above answer your question?

**Comment by marcgise** [comment]
Yes, it's OK. Thank you ;)

2017-03-04 17:05 GMT+01:00 Stefan Ferstl <notifications@github.com>:
