### ISSUE TITLE
Prevent generation of empty images

### ISSUE THREAD

**Issue by Wonno** [ferstl/depgraph-maven-plugin#26]
During generation of images I get a lot of  small empty image files cause of filtering.

I would suggest to omit image generation, if it will be empty anyway.

**Comment by ferstl** [comment]
At the moment, the graph contains only nodes that are either the source or the target of a dependency. In case a module does not have any dependencies (or if the dependencies are filtered), the graph will be empty.
I am planning to add the root module as node to the graph even if it does not have any dependencies. This will avoid empty images (except the root module is filtered) and will lead to a correct graph, i.e. showing a root node without dependencies.

**Comment by ferstl** [comment]
Version 2.2.0 will be on Maven Central within the next few hours.
