### ISSUE TITLE
Colored dependencies

### ISSUE THREAD

**Issue by ebourg** [ferstl/depgraph-maven-plugin#3]
I'd like to suggest a minor improvement to the graphs generated. The edges could be colored according to the type of the dependency. For example compile: black, provided: blue, test: green, etc.

**Comment by ferstl** [comment]
Yes, why not. But I would rather color the dependencies themselves instead of the edges. Colored edges might be confusing when the graph does not show omitted dependencies.

**Comment by ebourg** [comment]
Colored nodes would be fine too, but there may be a catch if an artifact is a test dependency of a module and a compile dependency of another module.

**Comment by ferstl** [comment]
In the current implementation, dependencies in different scopes will show up multiple times and the scope is displayed for all non-compile dependencies.

**Comment by victornoel** [comment]
Maybe the colored edge could make sense in conjunction with #10...

**Comment by ferstl** [comment]
Coming soon

**Comment by ferstl** [comment]
Check out the new [Styling capabilities](https://github.com/ferstl/depgraph-maven-plugin/wiki/Styling) in Version 2.0.1. The new version will be available on Maven Central within the next few hours.

**Comment by ebourg** [comment]
This looks excellent, thank you very much.
