### ISSUE TITLE
Better Outline of Duplicates and Conflicts

### ISSUE THREAD

**Issue by ferstl** [ferstl/depgraph-maven-plugin#30]
Show edges in a different style for duplicate and conflicting dependencies.

    graphics
    [
      style "dashed"
    ]

**Comment by Naxos84** [comment]
Please also make conflicting edges in red (for gml format) like it is done for the .dot format

[Duplicates and Conflicts Image](https://raw.githubusercontent.com/ferstl/depgraph-maven-plugin/master/src/doc/duplicates-and-conflicts.png)
So:

**Duplicate:**
graphics
[
  style "dotted" (or "dashed")
]

**Conflict:**
graphics
[
  style "dashed"
  fill     #FF0000
]

**Comment by ferstl** [comment]
The graph will now look like this in yEd:
![yEd](https://raw.githubusercontent.com/ferstl/depgraph-maven-plugin/feature/%2330-documentation/src/doc/yed.png)

I'll close this issue as soon as the plugin is released

**Comment by ferstl** [comment]
Version 2.2.0 will be on Maven Central within the next few hours.
