### ISSUE TITLE
Collapse dependencies

### ISSUE THREAD

**Issue by reckart** [ferstl/depgraph-maven-plugin#34]
It would be nice to have an option to hide the dependency edge between module A and C if A also depends on B and B on C.

**Comment by ferstl** [comment]
To understand you correctly, you have something like this:

    A -> B
    A -> C
    B -> C

And you want a dependency graph like `A -> B -> C` ?

**Comment by reckart** [comment]
I'm using the `aggregate` goal. 

I am suggesting this because in my case, I get a pretty dense graph. That is because I use the Maven Depenendency Plugin regularly to analyze dependencies and to tell my when I should add an explicit dependency between two modules A and C (i.e. when A is directly calling code from C) - even if C is already a transitive dependency of A via some B (A -> B -> C). To avoid potential problems with the Maven dependency resolution mechanism, this is a good idea. 

However, when trying to get a picture of the module architecture, then these extra dependencies create a lot of edges in the graph. With the ability to hide them, I believe one would get a clearer picture of the actual module architecture.

**Comment by ferstl** [comment]
> I'm using the `aggregate` goal.

I thought so. Unfortunately, Maven does not have an "overall" dependency view of a multi-module project. It resolves dependencies per module. What the `aggregate` goal does, is merge the individual dependency graphs into one graph. That's the reason why you might see more than one edge to a dependency (unlike the `graph` goal).

Probably, I can add an option to the `aggregate` goal that remembers each visited dependency and does not create an edge if the dependency was already visited.

If you have a module in your project that has dependencies for all other modules, you might try to use the `graph` goal on that module in the meantime. With that goal, you will get a real dependency tree, i.e. there is exactly one path to each dependency.

**Comment by reckart** [comment]
I tried using the graph goal, but doesn't provide the output I was looking for, even on a module that depends on all other modules. 

Consider this case (`->` means *depends on*)

```
A -> B
A -> C
B -> D
C -> D
A -> D
```

Then the first four edges should be visible, but not the last one. 

However, if I see it correctly, then using the `graph` mojo, only one of the two of the edges are visible which are either `A -> B` or `A -> C` and depending on that then `B -> D` or `C -> D`.

**Comment by ferstl** [comment]
Yes, that is correct. The `graph` goal shows exactly how Maven resolves the dependencies. So there will be exactly one path to each dependency (unless you enable the `showDuplicates` option). In the example above Maven will either omit the edge `C -> D` or `A -> D`.
I thought that was what you wanted to see in your graph,

Why should the edge `C -> D` in the graph besides the first three? With that edge, there wouldn't be a unique path to module `D`.

**Comment by reckart** [comment]
I am not only interested in unique paths - that is why the `graph` goal actually doesn't help me. I am interested in visualizing the way that modules form "layers" in the architecture. The `aggregate` goal works well for that. But some edges could be hidden because they are already covered by other edges. In the case of my example, we have a diamond structure:

```
     A
   / | \
  B  |  C
   \ | /
     D
```

Here, the dependency `A->D` is covered by the paths via B and C. However, the paths via B and C do not cover each other. Thus, `A->D` is redundant, but the others are not.

**Comment by reckart** [comment]
I guess the rule would be "do not draw a direct connection between X and Y if there is also an indirect connection between X and Y".

**Comment by ferstl** [comment]
Ok, I'll take a look.

**Comment by ferstl** [comment]
I implemented a new flag for the aggregated graphs called `reduceEdges` and it should do what you requested in this issue. The algorithm is somewhat like this:
- Create individual dependency graphs for each module by following the **reactor build order** of the modules
- Add a dependency edge `A -> B` only when there is not already a path between `A` and `B`.

This will reveal the "layers" in your project setup because an edge to a dependency will only be created when it appears for the first time in the reactor build order but not when it transitively appears again and is already reachable.

If you want to try it out, you can simply build the plugin and run it on your project:

```
git clone git@github.com:ferstl/depgraph-maven-plugin.git
cd depgraph-maven-plugin

#Tests will take a while
mvn clean install -DskipTests

cd your-project
mvn com.github.ferstl:depgraph-maven-plugin:2.2.1-SNAPSHOT:aggregate <add other options as you like>
```

The `reduceEdges` option is set to `true` by default. If you want to compare your graph to the old cluttered format, you can add `-DreduceEdges=false` to your maven command.
I might bump the version of the plugin to 3.0.0-SNAPSHOT in the next days. So you might need to adjust the maven command above accordingly.
The release of version 3.0.0 will hopefully be this month.

**Comment by ferstl** [comment]
Test dependencies will not be reduced since they are not transitive.

**Comment by ferstl** [comment]
Version 3.0.0 is available on Maven Central

**Comment by reckart** [comment]
Cool. That change provides a much better overview! Adding the option to switch back to the old view was also a great idea 👍
