### ISSUE TITLE
Support for OSGI bundle classifier

### ISSUE THREAD

**Issue by bfesq** [ferstl/depgraph-maven-plugin#38]
Thanks for this great tool it is invaluable in looking at a JBOSS Fuse upgrade project. 

Currently what I am facing is a problem with the general use of bundles and jars where the type is generally not defined. The plugin is identifying 2 nodes a bundle and a jar. I tried to exclude or include only what I need but had no luck. Appreciate any advice.

Thanks

Ben

**Comment by ferstl** [comment]
Hi,

Can you give me an example or do you have probably a project on GitHub to try?  Generally, the plugin considers the type of an artifact (but it does not show up in the graph). But with `includes` and `excludes` you can filter by type, e.g. `*:*:jar:*`.

**Comment by madmanu** [comment]
I have the same problem. It happens for bundles built using `maven-bundle-plugin`.

I solved it using `<mergeScopes>true</mergeScopes>`.

**Comment by ferstl** [comment]
@madmanu Yes, the scopes of dependencies can be merged into one node. However, the *type* of a dependency can not (classifiers can not either).

@bfesq Does `mergeScopes` solve your problem or is it really the type. Here you can find an example of `mergeScopes` (in the comments at the end): https://github.com/ferstl/depgraph-maven-plugin/issues/37

**Comment by bfesq** [comment]
Hi I tried merge scopes and didnt work, the type of jar or bundle still
came up as jar is assumed when type not declared I guess. I have simply
done some manual edits to adjust the diagram. Will try and find an example
to reproduce.

**Comment by ferstl** [comment]
@bfesq Ok, an example would be helpful. Have you tried filtering by type as I suggested in the second comment of this issue?

**Comment by madmanu** [comment]
@ferstl You are right, Bundles that differ only from a jar by their type are not merged.

However, I cannot filter them out because some dependency arrows start from the jar, and some others start from the bundle.

We may have both `bundle` and `jar` because of the way the Felix Maven plugin handles the bundle packaging.

Here is my minimal POM:
```
<project>
	<modelVersion>4.0.0</modelVersion>

	<groupId>x</groupId>
	<artifactId>y</artifactId>
	<version>z</version>
	<packaging>bundle</packaging>

	<dependencies>
...
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<extensions>true</extensions>
				<configuration>
...
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by ferstl** [comment]
I think introducing a `mergeTypes` option in the plugin would help. This option might also be set to `true` by default.

**Comment by ferstl** [comment]
Version 3.0.0 is available on Maven Central

**Comment by madmanu** [comment]
Thanks!
