### ISSUE TITLE
Add support for PlantUML

### ISSUE THREAD

**Issue by gushakov** [ferstl/depgraph-maven-plugin#39]
Hi, thank you for your work on this useful tool.

I submitted a PR for support for [PlantUML](http://plantuml.com/) diagrams (requires GraphViz installed, of course). There are minimal changes to the existing files and the integration is straight forward.

The support for PlantUML can be very helpful for the community of users of the IntelliJ CE. There is a very useful [plugin](https://plugins.jetbrains.com/plugin/7017-plantuml-integration) which allows to display the PlantUML diagrams **directly** in the workbench. Here is a preview of a PlantUML diagram created with your plugin in IntelliJ CE.

![image](https://user-images.githubusercontent.com/793519/27725817-594f30a4-5d78-11e7-8ec4-65f236ff094b.png)

There is, of course, some other work (support for custom styling, integration tests) which could be added later. Also, I did not try to run the licence generator for the new files.

Here is the link to PlantUML [Web Server](http://www.plantuml.com/plantuml) where you can try generating diagrams online.

Thanks again.

Cheers,

George

**Comment by gushakov** [comment]
After a bit of thought...

Maybe this functionality is not something the depgraph plugin should have/support "out of the box". After all, PlantUML are diagrams and **not graphs** per se. Also, they require GraphViz and "dot" option generates graphs (and images) with the same information.

So feel free to dismiss the PR, I'll just keep it in my fork (that's what they are for :) after all).

George

**Comment by ferstl** [comment]
@gushakov Good work, thank you! I merged the PR but will keep this issue open until a new release of the plugin is available (depends a bit on my schedule). The support for PlantUML is well isolated. So, no problem to integrate it.

**Comment by ferstl** [comment]
Version 3.0.0 is available on Maven Central
