### ISSUE TITLE
Different shapes for modules and external dependencies

### ISSUE THREAD

**Issue by ebourg** [ferstl/depgraph-maven-plugin#4]
Would it be possible to use different shapes for the modules and the external dependencies. For example a box for the modules and a circle for an external dependency.

**Comment by ferstl** [comment]
Coming soon

**Comment by ferstl** [comment]
Check out the new [Styling capabilities](https://github.com/ferstl/depgraph-maven-plugin/wiki/Styling) in Version 2.0.1. The new version will be available on Maven Central within the next few hours.
