### ISSUE TITLE
Add support for JavaScript libraries

### ISSUE THREAD

**Issue by connollyst** [ferstl/depgraph-maven-plugin#41]
Similar to issue #32 but much easier, it would be neat if this plugin could output data formats that could be interpreted by popular JavaScript libraries. It would be up to the user to load that library and inject the data, but that would be a preferable approach over installing GraphViz in some cases.

The trouble might be in picking which libraries to support as there are so many out there. Good candidates might include:
- vis.js: http://visjs.org/docs/network/
  - Could generate a 'data' structure which just contains edges/nodes and let the user configure the physics.
  - Or, could generate an 'options' structure which includes edges, nodes, physics, and other settings.
- sigmajs: http://sigmajs.org/
  - data structure is nodes and edges, all nodes need to be given x & y coordinates, I'm not sure if this plugin has the logic to figure out coordinates or if that's normally handled by GraphViz
- cytoscape: http://js.cytoscape.org/#notation/elements-json
  - data structure would be an 'elements' array, x & y coordinates are optional and cytoscape will use configuration to handle the layout.

**Comment by ferstl** [comment]
@connollyst I am unfortunately not familiar with any of the Javascript libraries. The solution in #32 generates a simple JSON file with nodes and edges which is then rendered by the library.
I guess other Javascript libraries work in a similar way.

What is not possible with the plugin is layouting. This is a complicated task and better handled by things like Graphviz.

**Comment by ferstl** [comment]
#32 is solved and provides a generic JSON output with nodes and edges and all information that the graph can have.

**Comment by connollyst** [comment]
Hi @ferstl, I think that'll cover my use case just fine. I'll try it out and put in a new ticket if I have any more specific comments.
Cheers!
