### ISSUE TITLE
customStyleConfiguration is not applied to my depgraph:aggregate

### ISSUE THREAD

**Issue by madmanu** [ferstl/depgraph-maven-plugin#42]
Hi,

I configured the plugin (version 2.2) in my multi-module project, in parent POM's `pluginManagement`. I can see the custom file configuration is properly loaded (using `printStyleConfiguration`).

The generated `.dot` uses `"graph"`and `"default-node"`, and none of the `"node-styles"` sub-elements. Even a catch-all configuration is not used :
```
{
	"graph": {
		"rankdir": "LR"
	},
	"default-node": {
		"fill-color": "#00ff00",
	},
	"node-styles": {
		"*": {
			"fill-color": "#ff0000",
		}
	}
}
```

Produced `.dot` starts with :
```
digraph "backend" {
  graph [rankdir="LR"]
  node [shape="ellipse",style="rounded",fillcolor="#00ff00",fontname="Helvetica",fontsize="14"]
  edge [fontsize="10",fontname="Helvetica"]
```
and then only contains simple node and edge definitions, like :
```
  // Node Definitions:
  "com.xxx:"[label=<yyy>]
  // Edge Definitions:
  "com.xxx:" -> "com.zzz:"
```

Am I missing something?

**Comment by ferstl** [comment]
@madmanu Can you show me how you execute the plugin? A snippet of your POM file your `mvn` command with all options regarding would be helpful.

**Comment by madmanu** [comment]
Running with :
```
mvn  -DdotExecutable="C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" depgraph:aggregate
```
/pom.xml :
```
<project>
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.xxx</groupId>
		<artifactId>backend-parent</artifactId>
		<version>1.1.0-SNAPSHOT</version>
		<relativePath>parent/pom.xml</relativePath>
	</parent>

	<artifactId>backend</artifactId>

	<packaging>pom</packaging>

	<modules>
		...many modules here...
	</modules>
</project>
```
/parent/pom.xml :
```
<project>
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.xxx</groupId>
	<artifactId>backend-parent</artifactId>
	<version>1.1.0-SNAPSHOT</version>

	<packaging>pom</packaging>

	<build>
		<pluginManagement>
				<plugin>
					<groupId>com.github.ferstl</groupId>
					<artifactId>depgraph-maven-plugin</artifactId>
					<version>2.2.0</version>
					<configuration>
						<includes>com.xxx.*:::</includes>
						<showDuplicates>true</showDuplicates>
						<showConflicts>true</showConflicts>
						<mergeScopes>true</mergeScopes>
						<graphFormat>dot</graphFormat>
						<imageFormat>png</imageFormat>
						<createImage>true</createImage>
						<printStyleConfiguration>true</printStyleConfiguration>
						<customStyleConfiguration>${project.build.directory}/../report/depgraph.config.json</customStyleConfiguration>
						<outputDirectory>${project.build.directory}/../report/</outputDirectory>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<dependencyManagement>
		<dependencies>
... many here ...
		</dependencies>
	</dependencyManagement>

	<dependencies>
... some here ...
	</dependencies>

	<pluginRepositories>
		<pluginRepository>
			<id>central</id>
			<name>bintray-plugins</name>
			<url>http://jcenter.bintray.com</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

</project>
```
/report/depgraph.config.json :
```
{
	"graph": {
		"rankdir": "LR"
	},
	"default-node": {
		"type": "ellipse",
		"fill-color": "#00ff00"
	},
	"node-styles": {
		"*": {
			"type": "polygon",
			"fill-color": "#ff0000"
		}
	}
}
```

**Comment by ferstl** [comment]
Your command line and POM (I was only interested in the configuration of the plugin) is fine. I tried to reproduce your problem with your style configuration and got a build failure.

The reason is that you need to *always* define a `type` in node stylings, like `box`, `ellipse`,  etc. When you define a `fill-color`, you also need to set `style` to `filled` as described [here](http://www.graphviz.org/doc/info/attrs.html#d:fillcolor). 

Could you modify your style configuration to this and try again?

    {
      "graph": {
        "rankdir": "LR"
      },
      "default-node": {
        "type": "ellipse",
        "fill-color": "#00ff00"
      },
      "node-styles": {
        "*": {
          "type": "ellipse",
          "style": "filled",
          "fill-color": "#ff0000"
        }
      }
    }

**Comment by madmanu** [comment]
Thanks for the feedback. Unfortunately, this doesn't change anything.

`default-node` styles are included in the `.dot` output, but none of the `node-styles`  subtrees.

**Comment by ferstl** [comment]
It's indeed a bug. After reproducing your example more accurately I can see it.

**Comment by ferstl** [comment]
Technical details:
The problem is in the implementation of the `StyleKey` class which handles `null` values not correctly when matching the entries in the style configuration.

**Comment by ferstl** [comment]
Release 2.2.1 fixes this problem. It will be on Maven Central within the next few hours. Please try again with the new version of the plugin.

**Comment by madmanu** [comment]
It works. Thanks!
