### ISSUE TITLE
'label' must always be in quotes in .dot files

### ISSUE THREAD

**Issue by marcelstoer** [ferstl/depgraph-maven-plugin#5]
The generated `dependency-graph.dot` file contains instructions such as:

```
"info.magnolia:magnolia-core:jar::provided" -> "servlets.com:cos:jar::provided"[label=05Nov2002]
```

`graphviz` fails to parse that because the `label` attribute must always be in quotes.

**Comment by ferstl** [comment]
According the the [DOT specification](http://www.graphviz.org/doc/info/lang.html), an ID is one of the following:

> - Any string of alphabetic ([a-zA-Z\200-\377]) characters, underscores ('_') or digits ([0-9]), not beginning with a digit;
> - a numeral [-]?(.[0-9]+ | [0-9]+(.[0-9]*)? );
> - any double-quoted string ("...") possibly containing escaped quotes (\")1;
> - an HTML string (<...>).
>
> An ID is just a string; the lack of quote characters in the first two forms is just for simplicity. There is no semantic difference between abc_2 and "abc_2", or between 2.34 and "2.34". Obviously, to use a keyword as an ID, it must be quoted.

Since we don't need to consider HTML or XML strings here, the simplest solution is indeed to just quote everything.

**Comment by ferstl** [comment]
Version 1.0.2 which fixes this issue will be available on Maven Central within the next few hours.
