### ISSUE TITLE
Replace deprecated Dependency Tree API

### ISSUE THREAD

**Issue by ferstl** [ferstl/depgraph-maven-plugin#7]
The latest version of maven-dependency-tree dropped the Maven2 dependency tree API. See https://issues.apache.org/jira/browse/MSHARED-420 .
Adjust the plugin to use the official dependency graph API.

**Comment by ferstl** [comment]
There is no replacement for the deprecated tree API. The maven-dependency-plugin does not use it anymore since version 3.0.

    if ( verbose )
    {
      // To fix we probably need a different DependencyCollector in Aether, which doesn't remove nodes which
      // have already been resolved.
      getLog().info( "Verbose not supported since maven-dependency-plugin 3.0" );
    }

**Comment by sparsick** [comment]
As in the Apache issue mentioned, the replacement for the old package `org.apache.maven.shared.dependency.tree` is the package `org.apache.maven.shared.dependency.graph`. Therefore, I think the access point for the new API is [DependencyGraphBuilder](https://maven.apache.org/shared/maven-dependency-tree/xref/org/apache/maven/shared/dependency/graph/DependencyGraphBuilder.html) .
