### ISSUE TITLE
Add possibility to skip scope on nodes

### ISSUE THREAD

**Issue by Witko** [ferstl/depgraph-maven-plugin#74]
As we can use the styling of edges to show which dependency is compile or test(or any other scope) it would be good to add a possibility to skip the scope on the nodes. S for example if 2 artifacts depend on junit one with scope test and other compile the node junit would be there only once - the edges would describe the scope.

**Comment by ferstl** [comment]
Hi @Witko 
Sorry, I somehow missed the issues that you reported...
Have looked at the `mergeScopes` option in the aggregated graphs? This option should do exactly that.

**Comment by ferstl** [comment]
I'm closing this issue now. If this did not answer your question, please re-open it.
