### ISSUE TITLE
includes in not support

### ISSUE THREAD

**Issue by keygod** [ferstl/depgraph-maven-plugin#84]
` <plugins>    
            <plugin>  
                    <groupId>com.github.ferstl</groupId>  
                    <artifactId>depgraph-maven-plugin</artifactId>  
                    <configuration>  
                        <includes>  
                            <include>org.framework:*</include>  
                        </includes>  
                    </configuration>  
                    <version>3.2.1</version>  
                </plugin>  
  	     </plugins>`

I get 

`digraph "sendinfo-admin" {
  node [shape="box",style="rounded",fontname="Helvetica",fontsize="14"]
  edge [fontsize="10",fontname="Helvetica"]

  // Node Definitions:

  // Edge Definitions:
}`

when I delete `includes `  like this 
  ` <plugin>
                    <groupId>com.github.ferstl</groupId>
                    <artifactId>depgraph-maven-plugin</artifactId>
                    <configuration>
                        
                            
                        
                    </configuration>
                    <version>3.2.1</version>
                </plugin>`

I get  

`digraph "sendinfo-admin" {
  node [shape="box",style="rounded",fontname="Helvetica",fontsize="14"]
  edge [fontsize="10",fontname="Helvetica"]

  // Node Definitions:
  "com.sendinfo.framework:sendinfo-core:jar"[label=<sendinfo-core>]
  "org.apache.commons:commons-lang3:jar"[label=<commons-lang3>]
  "com.sendinfo.framework:sendinfo-springmvc:jar"[label=<sendinfo-springmvc>]
  "org.springframework.data:spring-data-keyvalue:jar"[label=<spring-data-keyvalue>]
  "org.springframework.data:spring-data-commons:jar"[label=<spring-data-commons>]
  "org.springframework.data:spring-data-redis:jar"[label=<spring-data-redis>]
  "org.springframework:spring-tx:jar"[label=<spring-tx>]
  "org.springframework:spring-oxm:jar"[label=<spring-oxm>]
  "org.slf4j:jcl-over-slf4j:jar"[label=<jcl-over-slf4j>]
  "com.sendinfo.framework:sendinfo-redis:jar"[label=<sendinfo-redis>]
  "redis.clients:jedis:jar"[label=<jedis>]
  "org.apache.commons:commons-pool2:jar"[label=<commons-pool2>]
  "com.dyuproject.protostuff:protostuff-core:jar"[label=<protostuff-core>]
  "com.dyuproject.protostuff:protostuff-api:jar"[label=<protostuff-api>]
  "com.dyuproject.protostuff:protostuff-runtime:jar"[label=<protostuff-runtime>]
  "com.dyuproject.protostuff:protostuff-collectionschema:jar"[label=<protostuff-collectionschema>]
  "io.undertow:undertow-core:jar"[label=<undertow-core>]
  "org.jboss.xnio:xnio-api:jar"[label=<xnio-api>]
  "org.jboss.xnio:xnio-nio:jar"[label=<xnio-nio<font point-size="10"><br/>(runtime)</font>>]
  "org.springframework.boot:spring-boot-starter-undertow:jar"[label=<spring-boot-starter-undertow>]
  "io.undertow:undertow-servlet:jar"[label=<undertow-servlet>]
  "org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:jar"[label=<jboss-annotations-api_1.2_spec>]
  "io.undertow:undertow-websockets-jsr:jar"[label=<undertow-websockets-jsr>]
  "org.jboss.spec.javax.websocket:jboss-websocket-api_1.1_spec:jar"[label=<jboss-websocket-api_1.1_spec>]
  "javax.servlet:javax.servlet-api:jar"[label=<javax.servlet-api<font point-size="10"><br/>(provided)</font>>]
  "org.glassfish:javax.el:jar"[label=<javax.el>]`

**Comment by ferstl** [comment]
Hi,

Release 3.2.2 fixes this issue. It should be available on Maven Central within the next few hours. Please be aware that your include filter `org.framework:*` will only match dependencies with the exact groupId `org.springframework`. If you want to also have spring-boot or spring-data in your dependency graph, you need to adjust your filter to either `org.springframework.*:*` or `org.springframework*:*`
