### ISSUE TITLE
How to exclude test classifier deps

### ISSUE THREAD

**Issue by paul-hammant** [ferstl/depgraph-maven-plugin#90]
I would have thought that this would have done it, but does not:
```
mvn com.github.ferstl:depgraph-maven-plugin:aggregate -Dincludes="com.mycompany:*:*:compile"
```

I can't see a close example in the wiki :-(

**Comment by ferstl** [comment]
You could try `-Dscope=compile`. You can find a detailed description of this option in the [plugin documentation](https://ferstl.github.io/depgraph-maven-plugin/graph-mojo.html#scope).

The `includes` and `excludes` options do only work for dependencies where you have an explicit test classifier, e.g.

    <dependency>
      <groupId>com.mycompany</groupId>
      <artifactId>my-test-dependency</artifactId>
      <classifier>tests</classifier>
    </dependeny>

HTH

**Comment by paul-hammant** [comment]
Thanks - that makes sense, sorry for over focussing on whether includes could do it.
